### ISSUE TITLE
Feature Request: use syft as library

### ISSUE THREAD

**Issue by developer-guy** [ckotzbauer/sbom-operator#10]
A while ago I've asked from @wagoodman to describe how we can use syft as a go module, thanks to him, he created a gist for us. So, we can use syft as a go module instead of executing its binary.

👉  https://gist.github.com/wagoodman/57ed59a6d57600c23913071b8470175b

**Comment by developer-guy** [comment]
feel free to assign it to me if you agree on that

**Comment by ckotzbauer** [comment]
Uh, that's great! I really would prefer to use syft this way. Feel free to make a PR for that. I would appreciate it :+1: 
/kind feature
