### ISSUE TITLE
Feature Request: use ConfigMaps as an additional storage for SBOMs

### ISSUE THREAD

**Issue by developer-guy** [ckotzbauer/sbom-operator#110]
We (w/@dentrax) thought we could store SBOMs in a ConfigMap within the same cluster, so we should create a ConfigMap per container. One drawback of this approach would be the size limit of the ConfigMaps because Kubernetes allows us to store only 1MB of data within the ConfigMap. 

In addition to the idea, Falco announced its plugin system that allows us to create plugins to extend Falco's data sources, so we thought we could use SBOMs as input for Falco. We should develop a plugin to consume SBOns stored in ConfigMaps and apply rules on top of them.

**Comment by ckotzbauer** [comment]
@developer-guy @Dentrax
I'm currently thinking about ways to compress SBOMs to fit ConfigMap size-requirements. I used a modified [Spilo](https://github.com/zalando/spilo/blob/master/postgres-appliance/Dockerfile) image to generate sboms with syft (`json`, `spdx`, `cyclonedx`) and compressed them with gzip and brotli (highest compression-rate):

```
8,7M sbom.json
833K sbom.json.br
1,1M sbom.json.gz
1,2M sbom.spdx
67K sbom.spdx.br
74K sbom.spdx.gz
2,2M sbom.xml
96K sbom.xml.br
118K sbom.xml.gz
```

With brotli all sboms would be small enough in this example. The sbom-operator could do the compression and the falco-plugin has to decompress them again.

WDYT?

**Comment by ckotzbauer** [comment]
@developer-guy @Dentrax I opened a PR with the main-logic. Please have a look.
