### ISSUE TITLE
Feature request: Support Github App authentication

### ISSUE THREAD

**Issue by pawnu** [ckotzbauer/sbom-operator#141]
It's not possible to scope a PAT to a particular repository. The token you put into kubernetes cluster can be used to access all of your private repositories. I was wondering if it's possible to use Github App authentication which has been scoped to the Git source.

**Comment by ckotzbauer** [comment]
I think this should be possible without huge efforts. I like the idea. Maybe this is a good starting point: https://github.com/mlioo/go-github-app-token-generator

Would you mind open a PR for that?

**Comment by pawnu** [comment]
I can look into it when I get some time although I'm not very familiar with go. There will be some work required due to short expiration time of the app token.

https://docs.github.com/en/rest/apps/apps#create-an-installation-access-token-for-an-app
> Creates an installation access token that enables a GitHub App to make authenticated API requests for the app's installation on an organization or individual account. Installation tokens expire one hour from the time you create them.

**Comment by ckotzbauer** [comment]
fyi, I'm currently working on this.

**Comment by muellerst-hg** [comment]
Github provides deploy keys to authenticate non-human access at repository scope.
https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys

If your purpose is to push sboms to a single git repo, then deploy keys are the most simple solution.
