### ISSUE TITLE
Adding pod label as tags fails because ctx.Pod.Labels is always empty

### ISSUE THREAD

**Issue by muellerst-hg** [ckotzbauer/sbom-operator#193]
I was trying to test the new podLabelTagMatcher feature #172
However, I could not manage to get it working.

Reproduce with:
```gherkin
Given I add a new pod to the cluster with the following manifest
  ---
  apiVersion: v1
  kind: Pod
  metadata:
    namespace: test
    name: 172-demo
    labels:
      foo: bar
  spec:
    containers:
      - name: 172-demo
      image: alpine:3.13.0
      command:
        - sh
        - -c
      args:
        - while true; do sleep 10; done
When sbom-operator processes the pod for dtrack target
Then I expect ctx.Pod.Labels to contain the label "foo" with value "bar"
But instead ctx.Pod.Labels is an empty map
```

I was debugging [`newInfo.Labels` in processor.ListenForPods()](https://github.com/ckotzbauer/sbom-operator/blob/main/internal/processor/processor.go#L49) to make sure the regex matcher itself is not the issue.

`kubectl describe pod 172-demo` contains the label `foo=bar`

**Comment by ckotzbauer** [comment]
Found it: It needs to be added here too: https://github.com/ckotzbauer/sbom-operator/blob/5e28b829eb73e810cd1bfac237097d0b0a88d858/internal/kubernetes/kubernetes.go#L49
Would you mind opening a PR for that?
