### ISSUE TITLE
Dependency Track project names

### ISSUE THREAD

**Issue by giulio1979** [ckotzbauer/sbom-operator#319]
Hi, I have been trying to scan few clusters and publish to dependency track the results but I am not sure how to identify images that exist in multiple clusters at same time.

Could you tell me if this is possible or maybe using a custom project name in dtrack ? something like kubernetes cluster name + image name ?

**Comment by ckotzbauer** [comment]
Hi,
the projects are tagged with the cluster-name: `kubernetes-cluster=${clusterId}`. The `clusterId` if a sbom-operator parameter. When an image is part of multiple clusters it has multiple tags as specified above.
Does this answer your question?

**Comment by giulio1979** [comment]
Let me try, sounds logical
