### ISSUE TITLE
dtrack Base-URL

### ISSUE THREAD

**Issue by SasRei** [ckotzbauer/sbom-operator#376]
hi all,

We use DTrack behind an Nginx Reverse Proxy to be able to use SSL.

For reasons our dtrack-base-url is 'https://dtrack.example.com/api', but unfortunately it seems that everything following the / is truncated, no matter what i enter the sbom-operator uses the url "https://dtrack.example.com/api/v1/bom", instead of "https://dtrack.example.com/api/api/v1/bom" and is not able to Upload because of an DTrack API 400 Error.

Does anyone have a tip or hint for me?

regards
Sascha

**Comment by ckotzbauer** [comment]
Hi @SasRei,
thanks for your issue. I think this https://github.com/DependencyTrack/client-go would be the correct place to post this issue.

**Comment by SasRei** [comment]
Hi @ckotzbauer 

Ok, thought you maintained the dtrack_target.go .
Probably it is also enough to fork the repo and set the baseURL fixed, i'll give it a try. thank you

regards
Sascha

**Comment by ckotzbauer** [comment]
Yes, I maintain the dtrack_target.go, but I dont modify the url which is configured and only pass it to the library I posted.

**Comment by SasRei** [comment]
yeah, just saw it. you can delete this issue, thank you.
