### ISSUE TITLE
Integrate vulnerability scanning

### ISSUE THREAD

**Issue by ckotzbauer** [ckotzbauer/sbom-operator#6]
There are multiple possible options I have in mind:
- Trigger Github-Webhook to start a Github-Action for further analysis
- Built a standalone application to scan the generated SBOMs from this operator (can be triggered with webhook too)
- Expose metrics for found vulnerabilities (this would be also a feature which should be added to a standalone application)
...

/kind feature

**Comment by derkoe** [comment]
Could you use https://github.com/anchore/grype for that?

**Comment by ckotzbauer** [comment]
Yes, that's the plan :smile: 
I will start with the "vulnerability-operator" in the next few weeks.

**Comment by ckotzbauer** [comment]
Follow-up for standalone-project ckotzbauer/vulnerability-operator#1
