### ISSUE TITLE
Docker Image ID Parsing -- Could not parse

### ISSUE THREAD

**Issue by AkashSirimanna** [ckotzbauer/sbom-operator#68]
Image ID's are retrieved as follows: https://github.com/ckotzbauer/sbom-operator/blob/151dde7a4046091f2ea56eaaabfc900ced1800da/internal/kubernetes/kubernetes.go#L106-L122

And they are parsed as follows: https://github.com/ckotzbauer/sbom-operator/blob/151dde7a4046091f2ea56eaaabfc900ced1800da/internal/syft/syft.go#L42

I am seeing the following error logs:
```
time="2022-04-06T19:40:03Z" level=error msg="Could not parse imageID docker-pullable://<rest of image id>" error="Error parsing reference: \"docker-pullable://<rest of image id>\" is not a valid repository/tag"
```

I believe this is because the Image ID is prefixed with `docker-pullable://`

I writing a small program to parse `<rest of image id>` using the same library used by sbom-operator: `docker-parser`and it works fine.

I think the simplest fix to this is to either remove the `docker-pullable://` prefix or use the `img.Image` field instead.

**Comment by ckotzbauer** [comment]
Hi @AkashSirimanna,
thanks for opening this issue. Is my assumption correct, that your underlying container-runtime is docker?
This code was mainly tested with containerd, which seems to produce different values there.

**Comment by AkashSirimanna** [comment]
> Hi @AkashSirimanna, thanks for opening this issue. Is my assumption correct, that your underlying container-runtime is docker? This code was mainly tested with containerd, which seems to produce different values there.

Hi @ckotzbauer, yes the container runtime is docker. I would have expected the `docker-parser` library to support the `docker` container runtime but I guess not.

Do you think it'd be possible to add support for this? It could be as simple as removing the `docker-pullable://` prefix if it exists in the image id.

**Comment by ckotzbauer** [comment]
Yes, that would be possible. I would prefer to simply remove the prefix. I have to look if other major runtimes like CRI-O use a prefix too. Containerd does not.

**Comment by ckotzbauer** [comment]
Yes, correct.
No, the reason for this is: You can have multiple containers with the same image and different imageIDs, which could lead to different SBOMs. This ocurres often with floating tags.

**Comment by ckotzbauer** [comment]
If you want to work on it, you can do that. Otherwise I can fix that on the weekend.

**Comment by AkashSirimanna** [comment]
I can work on it. Just did a bit of work looking at image id formats for different container runtimes.

CRI-O
```
➜  ~ k get nodes -o wide
NAME       STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
minikube   Ready    control-plane,master   21h   v1.23.2   192.168.49.2   <none>        Ubuntu 20.04.1 LTS   5.10.76-linuxkit   cri-o://1.20.2
➜  ~ k get pod kube-apiserver-minikube -n kube-system -ojsonpath='{.status.containerStatuses[].imageID}'
k8s.gcr.io/kube-apiserver@sha256:1d600846bf9a45f1a6fa8134b88e8da47e2eedfc9be677ca1522afecc542fdde%
```

Docker
```
➜  ~ k get nodes -o wide
NAME       STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
minikube   Ready    control-plane,master   21h   v1.23.2   192.168.49.2   <none>        Ubuntu 20.04.1 LTS   5.10.76-linuxkit   docker://20.10.5
➜  ~ k get pod kube-apiserver-minikube -n kube-system -ojsonpath='{.status.containerStatuses[].imageID}'
docker://sha256:8a0228dd6a683beecf635200927ab22cc4d9fb4302c340cae4a4c4b2b146aa24%
```

Containerd
```
➜  ~ k get nodes -o wide
NAME       STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
minikube   Ready    control-plane,master   22h   v1.23.2   192.168.49.2   <none>        Ubuntu 20.04.1 LTS   5.10.76-linuxkit   containerd://1.4.4
➜  ~ k get pod kube-apiserver-minikube -n kube-system -ojsonpath='{.status.containerStatuses[].imageID}'
k8s.gcr.io/kube-apiserver@sha256:63ede81b7e1fbb51669f4ee461481815f50eeed1f95e48558e3b8c3dace58a0f%
```

Ill add support for those 3 runtimes (docker has 2 prefixes docker:// and docker-pullable://)

Ill link the PR once its ready

**Comment by ckotzbauer** [comment]
Thanks for the research. Highly appreciated 😇
