### ISSUE TITLE
Feature discussion: AWS Lambda SBOM generation

### ISSUE THREAD

**Issue by outofcoffee** [ckotzbauer/sbom-operator#74]
Hello - thank you for starting this project - it has saved me from attempting to build the same thing! ❤️ 

Would you be open to a contribution to allow SBOM generation from AWS Lambda functions?

Broadly, something like:

1. Use the AWS Lambda Go SDK to call the `GetFunction` operation, to obtain the `Code.Location` URL
2. Fetch the Lambda's function code from the URL to a local temporary dir; this is generally a ZIP file
3. Invoke Syft on the local code package
4. (Tidy up?)

This would enable use of this tool in an environment in which there is a mix of Kubernetes workloads and serverless ones.

I wanted to guage your interest in whether this aligns with your project goals, before contributing a PR.

**Comment by ckotzbauer** [comment]
Hi,
yes, this seems to be a valueable feature. I haven't any experience with AWS Lambda, but the approach seems comprehensible to me.

You can do a PR for that, and then we can discuss more in detail about the changes, but the concept looks well.

**Comment by ckotzbauer** [comment]
I started a refactoring in a feature-branch to allow other scan-items than containerImages. Maybe this could be a good entry-point for this feature.
https://github.com/ckotzbauer/sbom-operator/tree/feature/scan-item

**Comment by outofcoffee** [comment]
Thanks @ckotzbauer. I know that branch is old now - is that change merged into main or does it need a rebase?

**Comment by ckotzbauer** [comment]
The branch needs a rebase

**Comment by ckotzbauer** [comment]
@outofcoffee Do you still work on this?
